### ISSUE TITLE
Possible to mount a disk in the Spike run Linux

### ISSUE THREAD

**Issue by wsong83** [sycuricon/riscv-spike-sdk#30]
Since our internal work concentrates on revising Spike, we cannot use QEMU.
Then it comes a problem.

To be specific, I want to run the 525.x264_r SPEC CPU 2017 benchmark case, which needs to decode a 1.7GB video file.
I think it is obviously that I cannot put this large file into the ramfs and ask the kernel to load it to memory in a emulated way.
This is too slow, especially we have replace the Spike's cache with our own model!

Is there a way to mount a disk from the host when running inside the Linux on Spike.
Or, may be there is a way to ask Spike to emulate a host file as a virtual drive using the device/bitbang?

Any suggestion would be appreciated.

**Comment by Phantom1003** [comment]
Hey, long time : )  It seems like you need to implement two parts of the functionality.
- First, you need to allow Spike to take over your resources.
- Second, you need to allow the software on Spike to handle your resources. 

There used to be some device emulation available in Spike's fesvr. However, very few people seem to be using it at the moment.  You can use [HTIF](https://github.com/riscv-software-src/riscv-isa-sim/blob/e8d1f8d21c5ae8567d1ab4a4db366bcb9ed55995/fesvr/htif.cc#L328C14-L331) to mount a disk device, but you'll need to write your own kernel driver. 

Alternatively, you can use the drivers in the kernel, but you'll need to write a disk device yourself based on the driver you selected. I recommend this option for easier maintenance of your extension.

These methods can give you a better system booting experience, but I don't think you'll get a significant speedup in your evaluation either way. This is because the filesystem stack plus the emulation of disk behavior will both make you slower than if you were accessing data mapped directly into memory.

**Comment by wsong83** [comment]
Wow, it really makes me feel happy for knowning at I am remembered ;-) 

cc @lazyparser , maybe he knows something and would chime in (I am not sure whether this would automatically pin him).

I am not totally sure for my following remarks:

For waht I understand, the HTIF disk_t emulates a disk at the syscall level, as the frontend server acts as the kernel. However, what I need is to have a disk emulated at the SBI level? I am not a driver/firmware guy, knowing too little about them. Revising some parts of Spike seems feaible to me. So, perhaps the alternative way is the only way forward?

If, say, I would like to implement an emulated disk backed by a file on the host machine, which existing kernel driver do you recommend? Is there any similar project/code at wild that I can learn about?

I am currently using BBL and know very little about OpenSBI. Is this a problem?

What in my mind is something like: `spike --disk host-image-file bbl`, and this host-image-file is then mmapped into host memory by Spike. A Linux kernel driver allows me to mount a disk during or after booting the kernel. This driver talks with Spike through SBI.

Many thanks!

**Comment by Phantom1003** [comment]
> However, what I need is to have a disk emulated at the SBI level?  ... This driver talks with Spike through SBI.

It seems that the first option aligns better with your requirements. In fact, there is still a valid console driver in the kernel that you can refer to by accessing this [link](https://elixir.bootlin.com/linux/latest/source/drivers/tty/hvc/hvc_riscv_sbi.c). This kernel driver is responsible for forwarding the syscall to the host through the SBI calls. BBL/OpenSBI communicates with the host by writing/reading magic numbers to/from the tohost/fromhost section. The disk emulation process is quite similar, as htif can also directly emulate a disk device.

> I am currently using BBL and know very little about OpenSBI. Is this a problem?

OpenSBI is compatible with BBL (a.k.a., legacy sbi or sbi 0.1), and currently, it is the most widely used option for distribution. Although BBL is simple enough, it has very limited functionality, and it takes a lot of effort for us to maintain the flow that boots Linux with BBL. However, for your customization, I believe you can simply select those reserved SBI call numbers, and this should not be a problem.

> Which existing kernel driver do you recommend? Is there any similar project/code at wild that I can learn about?

If you don't want to write kernel driver, then VirtIO I suppose, a good starting point may be Fabrice Bellard's [TinyEMU](https://bellard.org/tinyemu) (or the qemu), which has implemented PCI bus and virtio devices.

**Comment by wsong83** [comment]
FYI, we have implemented a mountable disk image reusing the virtio driver in Linux, and the spike-devices repo.
Our extension to spike-devices is here: https://github.com/comparch-security/spike-devices
Thanks very much for the valuable suggestions!

**Comment by Phantom1003** [comment]
It's impressive that the functionality can be achieved without using the PCI bus. I've always wanted to implement a set of abstract, compatible, and simple device models on FPGA. This would be a meaningful effort.
